# -*- mode: ruby -*-
# vi: set ft=ruby :

require (ENV['OPERATOR_HOME'] + '/vagrant/lib/common/module/paths.rb')
include CommonPaths

Vagrant.configure("2") do |vagrant|
  vm = SETTINGS['local']['vm']
  jenkins = SETTINGS['local']['server']['jenkins']

  vagrant.vm.box = vm['box']
  # vagrant.vm.network "forwarded_port", guest: 80, host: 8080
  vagrant.vm.network "private_network", ip: jenkins['ip']

  vagrant.vm.synced_folder '.', '/vagrant', disabled:true

  vagrant.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = jenkins['memory']
    vb.cpus = jenkins['cpus']
    vb.name = jenkins['hostname']

  end

  vagrant.ssh.insert_key = false
  vagrant.vbguest.auto_update = SETTINGS['local']['vbguest']['auto_update']

  eval File.read( COMMON + '/provision.rb' )

end
